import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['Italia'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['Comida rápida', 'Pizza', 'Almuerzo'],
  },
  {
    id:'2',
    name: 'Albóndiga',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['Oriente Medio', 'China'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['Comida lenta', 'Almuerzo'],
  },
  {
    id:'3',
    name: 'Hamburguesa',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['Alemania', 'USA'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['Comida rápida', 'Hamburguesa'],
  },
  {
    id:'4',
    name: 'Papas fritas',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['Bélgica', 'Francia'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['Comida rápida', 'Freír'],
  },
  {
    id:'5',
    name: 'Sopa de pollo',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['India', 'Asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['Comida lenta', 'Sopa'],
  },
  {
    id:'6',
    name: 'Pizza de Verduras',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['Italia'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['Comida rápida', 'Pizza', 'Almuerzo'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'Todos', count: 6 },
  { name: 'Comida rápida', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Almuerzo', count: 3 },
  { name: 'Comida lenta', count: 2 },
  { name: 'Hamburguesa', count: 1 },
  { name: 'Freír', count: 1 },
  { name: 'Sopa', count: 1 },
]
